repos:
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.9
    hooks:
      - id: ruff
        args: ["--fix"]

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.13.2
    hooks:
      - id: isort
        additional_dependencies: ["tomli"]

  - repo: local
    hooks:
      - id: cargo-fmt
        name: cargo fmt
        entry: bash -c 'cargo fmt --all'
        language: system
        pass_filenames: false
      - id: cargo-clippy
        name: cargo clippy
        entry: bash -c 'cargo clippy --workspace --all-targets'
        language: system
        pass_filenames: false
